### ISSUE TITLE
numpy Thing Descriptions are broken

### ISSUE THREAD

**Issue by rwb27** [labthings/labthings-fastapi#79]
Swapping the unpleasant `NDArray` type for `pydantic-numpy` broke Thing Descriptions that included numpy array types. I will switch back to the built-in NDArray type, and will figure out a way to migrate to something better, ideally not written by me, in due course.

I think part of the problem is probably that I was hoping to use the model directly to generate a data schema for the Thing Description. I don't think this is likely to be possible with `pydantic-numpy`, but maybe there's a way to add some logic to serialise arrays in a helpful way. This is also something that will need thought if/when we add support for packed binary formats, which would be the best way to transport `numpy` data.

**Comment by VigneshVSV** [comment]
Can you give an example ? I could not exactly understand how to fit in a numpy array type in TD because its a CPP type and not a JSON type. 

I currently use msgspec serializer, which is a fast serilializer for JSON to convert numpy to JSON, which means the content type is still application/json and the data type is array with item type number or integer. There is still some overhead for large arrays.

Also in javascript, I dont there is a native numpy container to JS container deserializer. 

For python-to-python, I prefer using MessagePack serializer (again with msgspec) and setting content type to bytes. This gives the fastest performance for numpy arrays.
